Local models and other modification
OpenBMB/RepoAgent pull request #76
Opened 2024-08-16 17:08 UTC by Tesla2000

I am open to a discusion about some changes I added. Especially controversial can be removal of context length check which allows more flesibility in model choice and replacement of setting from config file with default which in my opinion makes it much more intuitive to use. It anything I would be pleased if you merge in change from repo_agent/utils/gitignore_checker.py which I believe is a bugfix. Previous behaviour caused indexing of gitignore files including .venv which shouldn't be the case

2024-08-18 15:09 UTC, Umpire2018 requested changes
Overall, this PR addresses the following points:

- **Formatting Changes:** You've done a great job ensuring the files are neatly formatted using a formatting tool. However, I believe that these changes should not be bundled with this PR. According to best practices, a PR should ideally focus on a single concern, and mixing formatting with functional changes can make it harder to review.

- **Introduction of response_generators:** I appreciate your effort to introduce response_generators for unified support of OpenAI and Huggingface models. However, I'm not entirely in favor of this approach. A potentially better solution might be to incorporate the `litellm` library, which could provide more streamlined multi-model support.

- **Env Support for API Configuration:** You've also introduced env support to configure API keys and related information. While this is a thoughtful addition, it doesn't align with the current project's approach of using the `pydantic_setting` library in combination with TOML for configuration. Therefore, I don't think this change should be included.

- **Fix typo:** From `latest_verison_substring` to `latest_version_substring`.

2024-08-18 15:09 UTC, Umpire2018 commented on repo_agent/utils/gitignore_checker.py
> +        self.folder_patterns += setting.project.ignore_list
> It anything I would be pleased if you merge in change from repo_agent/utils/gitignore_checker.py which I believe is a bugfix. Previous behaviour caused indexing of gitignore files including .venv which shouldn't be the case.

Can you open a new issue to discuss this problem and provide more details?

2024-09-14 20:02 UTC, Tesla2000 commented
You are right about litellm I wasn't aware of this library. I see you already added self.folder_patterns += setting.project.ignore_list. You have one more latest_verison_substring in meta_info_utils.py

2024-09-14 20:02 UTC, Tesla2000 commented
You may close this PR

2024-09-16 04:31 UTC, closed without merging